### ISSUE TITLE
Docker / Linux Support (BUG)

### ISSUE THREAD

**Issue by STDGA** [GleamTech/FileUltimate#12]
Hi,
if you add a Docker support (Linux) to the provided example .net core project, you can not start it any more.
It will fail with the following error:

`
System.ArgumentException: An item with the same key has already been added. Key: FileUltimate
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at GleamTech.Globalization.LanguageManager.Register(String name, LanguageManager languageManager)
   at GleamTech.FileUltimate.AspNet.FileUltimateWebConfiguration._4b()
   at GleamTech.FileUltimate.AspNet.FileUltimateWebConfiguration._xb()
   at GleamTech.FileUltimate.AspNet.FileUltimateWebConfiguration._sB()
   at GleamTech.AspNet.GleamTechWebConfiguration.OnApplicationStarted()
   at GleamTech.AspNet.Core.WebActivationMiddleware.Invoke(HttpContext context, IHostingEnvironment env)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

Do you have any idea how to fix this?

**Comment by GleamTech** [comment]
FYI, this is now fixed and Docker is supported.

## GleamTech.Common Version 4.3.0 - September 15, 2020

  - **Added:** "ASP.NET Core on Linux" support. PhysicalFileSystem will work correctly.
    Used PhysicalPath instead of BackSlashPath in many places (eg. Hosting.ResolvePhysicalPath).
    **Fixed CultureManager for some different culture name handling (e.g. "zh-Hans") on Linux.**


## GleamTech.FileUltimate Version 7.7.0 - September 15, 2020

  - **Added:** Initial "ASP.NET Core on Linux" support, everything works except these features:

    - Image thumbnails are not available as ImageUltimate does not support Linux yet (due to Windows native DLL dependency).

    - Video thumbnails are not available as videoUltimate does not support Linux yet (due to Windows native DLL dependency).

    - Image Viewer supports only image extensions .jpg, .png, .gif (not all image formats).

    - DocumentViewer is not available as PortableEngine in DocumentUltimate does not support Linux yet (due to Windows native DLL dependency).
    
  - **Improved:** Updated AssemblyResolver (4.1.0.0) for initial Linux support (no unnecessary extraction of Windows native DLLs).
